### ISSUE TITLE
Can't Create a Product

### ISSUE THREAD

**Issue by hyph3n** [aaronweaver/defectdojo_api#1]
Hello! I've installed a test instance of Defect Dojo and installed this client API using pip. Unfortunately, the example code provided in the README.rst does not seem to work as expected, and I'm not sure why. Here's what I'm seeing:

`>>> from defectdojo_api import defectdojo`
`>>> host = 'http://localhost:8000/'`
`>>> api_key = '<removed key for posting issue on github>'`
`>>> user = 'admin'`
`>>> dd = defectdojo.DefectDojoAPI(host, api_key, user, debug=False)`
`>>> prod_type = 1`
`>>> product = dd.create_product("API Product Test", "This is a detailed product description.", prod_type)`
`>>> if product.success:`
`...     product_id = product.id()`
`...     print "Product successfully created with an id: " + str(product_id)`
`... `
`>>> `
`>>> if not product.success:`
`...     print "Something failed."`
`... `
`Something failed.`
`>>> `

The terminal window running the Defect Dojo server shows the following:

`[21/Jul/2017 18:59:18] "POST //api/v1/products/ HTTP/1.1" 404 35510`

Another set of eyes might see where I've made a mistake as compared to the example code, so please feel free to tell me if I'm being dumb here.

Maybe the double '/' is causing a problem? Unfortunately my python skills are not exactly advanced, so I'm having some trouble figuring out what I should do here.

Thanks for whatever help you can offer!

**Comment by aaronweaver** [comment]
Sorry missed seeing this. As you suspected it's probably the double '/'
