### ISSUE TITLE
create_finding out of sync with REST-API

### ISSUE THREAD

**Issue by Horst88** [aaronweaver/defectdojo_api#10]
Hi Aaron,

create_finding does not include all attributes of the REST-API. Can you add the new attributes?

Python-API
       :param id: Engagement id.
        :param name: Engagement name.
        :param product_id: Product key id..
        :param lead_id: Testing lead from the user table.
        :param status: Engagement Status: In Progress, On Hold, Completed.
        :param target_start: Engagement start date.
        :param target_end: Engagement end date.
        :param active: Active
        :param pen_test: Pen test for engagement.
        :param check_list: Check list for engagement.
        :param threat_model: Thread Model for engagement.
        :param risk_path: risk_path
        :param test_strategy: Test Strategy URLs
        :param progress: Engagement progresss measured in percent.

REST-API
{
  "line_number": "",
  "product": "related",
  "description": "",
  "reporter": "related",
  "sourcefile": "",
  "under_review": false,
  "thread_id": 0,
  "mitigated": "datetime",
  "references": "",
  "date": "date",
  "active": false,
  "payload": "",
  "under_defect_review": false,
  "impact": "",
  "false_p": false,
  "verified": false,
  "severity": "",
  "is_template": false,
  "title": "",
  "url": "",
  "engagement": "related",
  "duplicate": false,
  "param": "",
  "id": 0,
  "sourcefilepath": "",
  "mitigation": "",
  "numerical_severity": "",
  "test": "related",
  "out_of_scope": false,
  "cwe": 0,
  "last_reviewed": "datetime",
  "resource_uri": ""
}

**Comment by aaronweaver** [comment]
Added several of the fields, let me know if there was a specific one you needed.
