### ISSUE TITLE
Unable to provide import path for the example files

### ISSUE THREAD

**Issue by siddse7en** [aaronweaver/defectdojo_api#2]
Hello,

I am trying to use the defectdojo_api file provided with this package instead of the default installation in the library package. 

I tried appending the os.path of the defectdojo module in __init.py__ inside examples folder. 
I tried to manually add the path in the dojo_ci_cd.py file itself. 

Basically I have tried these things: https://stackoverflow.com/questions/14132789/relative-imports-for-the-billionth-time
None of the methods are working. It is still picking the default installation of defectdojo.

**Comment by aaronweaver** [comment]
Set the pythonpath:

export PYTHONPATH=/path/totheapi/defectdojo_api:$PYTHONPATH
