### ISSUE TITLE
List_users() is not sending the params parameter

### ISSUE THREAD

**Issue by siddse7en** [aaronweaver/defectdojo_api#3]
Hi,

There is a hard coding in the dojo_cd_ci.py example where the user is always "admin" and the user_id is taken in a wrong way. It would be great if we could find the user list based on the username that we pass in the arguments.
dd.list_users(user) on line 72

In the list_users() function under defectdojo_api, even though you pass username and limit, it is ignored. 
The request sent as of now:
return self._request('GET', 'users/')
This can be the new request
return self._request('GET', 'users/', params)

Thanks!

**Comment by aaronweaver** [comment]
Pull request sent from @siddse7en to correct.
