### ISSUE TITLE
Problem using service for create engagement

### ISSUE THREAD

**Issue by Horst88** [aaronweaver/defectdojo_api#5]
Hi,
I get the following error trying to create an engagement over the API.

Traceback (most recent call last):
  File "/home/xxx/PycharmProjects/blub/upload.py", line 54, in <module>
    upload_scanreport(1, "opt/zap/xxx.xml", "ZAP Scan")
  File "/home/xxx/PycharmProjects/blub/upload.py", line 34, in upload_scanreport
    engagement_id = engagement.id()
  File "/usr/local/lib/python2.7/dist-packages/defectdojo_api/defectdojo.py", line 744, in id
    raise ValueError('Object not created:' + json.dumps(self.data, sort_keys=True, indent=4, separators=(',', ': ')))
ValueError: Object not created:{
    "error": "[u\"'true' value must be either True or False.\"]"

It looks like the API is using strings for booleans objects ('true') and that defect dojo changed the REST service to use actual booleans. -> true instead of 'true'.
Can you fix that?

Regards,

Horst

**Comment by aaronweaver** [comment]
@Horst88 Let me check.

**Comment by aaronweaver** [comment]
Can you try updating the api from pip? I updated this just recently to address this issue and a couple other items. I just verified that it works with this small test script.

```
from defectdojo_api import defectdojo
from datetime import datetime, timedelta

host = "http://localhost:8000"
api_key = ""
user = ""
user_id = 1
product_id = 1

proxies = {
  'http': 'http://localhost:8080',
  'https': 'http://localhost:8080',
}

dd = defectdojo.DefectDojoAPI(host, api_key, user, verify_ssl=False, proxies=proxies, timeout=360, debug=False)

start_date = datetime.now()
end_date = start_date+timedelta(days=180)

engagement_id = dd.create_engagement("Test From API", product_id, user_id, "In Progress", start_date.strftime("%Y-%m-%d"), end_date.strftime("%Y-%m-%d"))
print engagement_id
```

**Comment by Horst88** [comment]
Fixed from my point of view. Thanks a lot!!!
